DROP TABLE IF EXISTS GRANDPRIX CASCADE;
DROP TABLE IF EXISTS RESULTS CASCADE;
DROP TABLE IF EXISTS CAR CASCADE;
DROP TABLE IF EXISTS PILOT CASCADE;

CREATE TABLE GRANDPRIX
(
    GRANDPRIXID   INTEGER NOT NULL,
    GRANDPRIXNAME TEXT,
    PRIMARY KEY (GRANDPRIXID)
);

CREATE TABLE RESULTS
(
    GRANDPRIXID      INTEGER NOT NULL,
    BASELINEPOSITION INTEGER NOT NULL,
    FOREIGN KEY (GRANDPRIXID) REFERENCES GRANDPRIX (GRANDPRIXID),
    PRIMARY KEY (GRANDPRIXID, BASELINEPOSITION)
);

CREATE TABLE CAR
(
    BASELINEPOSITION INTEGER NOT NULL,
    CARNAME          TEXT    NOT NULL,
    PRIMARY KEY (BASELINEPOSITION, CARNAME)
);

CREATE TABLE PILOT
(
    PILOTID   INTEGER NOT NULL,
    PILOTNAME TEXT    NOT NULL,
    PRIMARY KEY (PILOTID)
);

INSERT INTO GRANDPRIX
VALUES (1, 'GRANDPRIX MONAKO');
INSERT INTO GRANDPRIX
VALUES (2, 'GRANDPRIX VIETNAM');

INSERT INTO RESULTS
VALUES (1, 56);
INSERT INTO RESULTS
VALUES (2, 56);

INSERT INTO CAR
VALUES (56, 'MACLAREN');
INSERT INTO CAR
VALUES (56, 'FERRARI');

INSERT INTO PILOT
VALUES (124, 'N. LAUDA');
INSERT INTO PILOT
VALUES (123, 'N. LAUDA');


SELECT *
FROM GRANDPRIX
         NATURAL JOIN PILOT
         NATURAL JOIN CAR
         NATURAL JOIN RESULTS;

-- GRANDPRIXID --> GRANDPRIXNAME