DROP TABLE IF EXISTS GRANDPRIX CASCADE;
DROP TABLE IF EXISTS RESULTS CASCADE;
DROP TABLE IF EXISTS BASELINE CASCADE;
DROP TABLE IF EXISTS PILOT CASCADE;

CREATE TABLE GRANDPRIX
(
    GRANDPRIXID   INTEGER NOT NULL,
    GRANDPRIXNAME TEXT,
    PRIMARY KEY (GRANDPRIXID)
);

CREATE TABLE PILOT
(
    PILOTID   INTEGER NOT NULL,
    PILOTNAME TEXT    NOT NULL,
    PRIMARY KEY (PILOTID)
);

CREATE TABLE RESULTS
(
    GRANDPRIXID      INTEGER NOT NULL,
    BASELINEPOSITION INTEGER NOT NULL,
    PILOTID          INTEGER NOT NULL,
    FOREIGN KEY (PILOTID) REFERENCES PILOT (PILOTID),
    FOREIGN KEY (GRANDPRIXID) REFERENCES GRANDPRIX (GRANDPRIXID),
    PRIMARY KEY (GRANDPRIXID, BASELINEPOSITION)
);

CREATE TABLE BASELINE
(
    BASELINEPOSITION INTEGER NOT NULL,
    CARNAME          TEXT    NOT NULL,
    PILOTID          INTEGER NOT NULL,
    FOREIGN KEY (PILOTID) REFERENCES PILOT (PILOTID),
    PRIMARY KEY (BASELINEPOSITION, CARNAME)
);



INSERT INTO GRANDPRIX
VALUES (1, 'GRANDPRIX MONAKO');
INSERT INTO GRANDPRIX
VALUES (2, 'GRANDPRIX VIETNAM');

INSERT INTO PILOT
VALUES (124, 'N. LAUDA');
INSERT INTO PILOT
VALUES (123, 'N. LAUDA');

INSERT INTO RESULTS
VALUES (1, 56, 123);
INSERT INTO RESULTS
VALUES (2, 56, 124);

INSERT INTO BASELINE
VALUES (56, 'MACLAREN', 123);
INSERT INTO BASELINE
VALUES (56, 'FERRARI', 124);

SELECT *
FROM GRANDPRIX
         NATURAL JOIN PILOT
         NATURAL JOIN BASELINE
         NATURAL JOIN RESULTS;