DROP TABLE IF EXISTS GLOBAL_MONEY CASCADE ;
DROP TABLE IF EXISTS EURO;
DROP TABLE IF EXISTS USD;
DROP TABLE IF EXISTS POUND;
DROP TABLE IF EXISTS GRAPHNODE CASCADE ;
DROP TABLE IF EXISTS ISOTIMIA;

CREATE TABLE GLOBAL_MONEY(
    NAME TEXT,
    PRIMARY KEY (NAME)
);

CREATE TABLE EURO(
    PRIMARY KEY (NAME)
) INHERITS (GLOBAL_MONEY);

CREATE TABLE USD(
    PRIMARY KEY (NAME)
) INHERITS (GLOBAL_MONEY);

CREATE TABLE POUND(
    PRIMARY KEY (NAME)
) INHERITS (GLOBAL_MONEY);

INSERT INTO EURO VALUES ('EURO');
INSERT INTO USD VALUES ('USD');
INSERT INTO POUND VALUES ('POUND');

CREATE TABLE GRAPHNODE(
    NODEKEY TEXT NOT NULL,
    FACET   TEXT,
    PRIMARY KEY (NODEKEY)
);

CREATE TABLE ISOTIMIA (
    NODEKEY1 TEXT NOT NULL ,
    NODEKEY2 TEXT NOT NULL ,
    VALUE FLOAT NOT NULL ,
    PRIMARY KEY (NODEKEY1, NODEKEY2),
    FOREIGN KEY (NODEKEY1) REFERENCES GRAPHNODE(NODEKEY),
    FOREIGN KEY (NODEKEY2) REFERENCES GRAPHNODE(NODEKEY)
);

INSERT INTO GRAPHNODE VALUES ('EURO', 'CURRENCY');
INSERT INTO GRAPHNODE VALUES ('USD', 'CURRENCY');
INSERT INTO GRAPHNODE VALUES ('POUND', 'CURRENCY');

INSERT INTO ISOTIMIA VALUES ('EURO', 'USD', 1.4);
INSERT INTO ISOTIMIA VALUES ('EURO', 'POUND', 1.2);
INSERT INTO ISOTIMIA VALUES ('USD', 'POUND', 0.8);

SELECT * FROM ISOTIMIA;